import numpy as np
array1=np.array([1, 2, 3])
array2=np.array([4, 5, 6])
print("Sum: ",array1+array2)
print("Subtraction: ",array1-array2)
print("Multiplication: ",array1*array2)
print("Division: ",array1/array2)
print("Power: ",array1**array2)
print("Modulus: ",array1%array2)
print("Floor Division: ",array1//array2)