import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
print("Addition of two arrays: ", array1 + array2)
print("Multiplication of two arrays: ", array1 * array2)
print("Dot product of two arrays: ", np.dot(array1, array2))
print("Square of array1: ", np.square(array1))
print("Maximum of array1: ", np.max(array1))
print("Minimum of array1: ", np.min(array1))
print("Mean of array1: ", np.mean(array1))
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array: \n", two_d_array)
print("Row-wise sum of 2D array: ", np.sum(two_d_array, axis=1))
print("Column-wise sum of 2D array: ", np.sum(two_d_array, axis=0))