import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3],[4, 5, 6]])
print("Array 1:",array1)
print("Dimensions:",array1.ndim)
print("Array 2:",array2)
print("Dimensions:",array2.ndim)
print("Shape of Array 1:",array1.shape)
print("Shape of Array 2:",array2.shape)
print("Size of Array 1:",array1.size)
print("Size of Array 2:",array2.size)
print("Data type of Array 1:",array1.dtype)
print("Data type of Array 2:",array2.dtype)
print("Item size of Array 1:",array1.itemsize)
print("Item size of Array 2:",array2.itemsize)