import numpy as np
A=np.array([[1, 2], [3, 4]])
B=np.array([[5, 6], [7, 8]])
print("A:\n", A)
print("B:\n", B)
print("A + B:\n", A + B)
print("A - B:\n", A - B)
print("A * B:\n", A * B)
print("A @ B:\n", A @ B)
print("A.T:\n", A.T)
